version: '3.1'

services:
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: super-app
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 8080:80 # Change this to map to port 80 of the container
    depends_on:
      - db
